MVC_GerenciadorDeCont/Controllers/MyCartController.cs
using Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVC_GerenciadorDeCont.Controllers
{
    public class MyCartController : Controller
    {

        public ActionResult Index()
        {
            var data = this.GetDefaultData();
            return View(data);
        }


        //Remove os Produtos
        public ActionResult Remove(int id)
        {
            TempShpData.items.RemoveAll(x => x.ProductID ==id); 
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ProcedToCheckout(FormCollection formcoll)
        {
            var a = TempShpData.items.ToList();
            for (int i = 0; i < formcoll.Count / 2; i++)
            {

                int pID = Convert.ToInt32(formcoll["shcartID-" + i + ""]);
                var ODetails = TempShpData.items.FirstOrDefault(x => x.ProductID == pID);


                int qty = Convert.ToInt32(formcoll["Qty-" + i + ""]);
                ODetails.Quantity = qty;

                TempShpData.items.RemoveAll(x => x.ProductID == pID);

                if (TempShpData.items == null)
                {
                    TempShpData.items = new List<OrderDetail>();
                }
                TempShpData.items.Add(ODetails);

            }

            return RedirectToAction("Index", "CheckOut");
        }
    }
}

MVC_GerenciadorDeCont/Controllers/ProductController.cs
using Business;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MVC_GerenciadorDeCont.Controllers
{
    public class ProductController : Controller
    {

        public ActionResult Index()
        {            
            return View("Products");
        }        

        //Adicione ao Carrinho
        public ActionResult AddToCart(int id)
        {
            OrderDetail OD = new OrderDetail();
            OD.ProductID = id;
            int Qty = 1;
            var price = Produto.BuscaPorId(id).UnitPrice;
            OD.Quantity = Qty;
            OD.UnitPrice = price;
            OD.TotalAmount = Qty * price;  
            OD.Produto = Produto.BuscaPorId(id);

            if (TempShpData.items == null)
            {
                TempShpData.items = new List<OrderDetail>();
            }
            TempShpData.items.Add(OD);            

            return Redirect(TempData["returnURL"].ToString());

        }

        //Detalhes do Produtos
        public ActionResult ViewDetails(int id)
        {
            var prod = Produto.BuscaPorId(id);           

            this.GetDefaultData();
            return View(prod);
        }        
    }
}

MVC_GerenciadorDeCont/Views/Shared/_CartBox.cshtml
@if (ViewBag.cartBox != null)
{
    foreach (var item in @ViewBag.cartBox)
    {
        <li>
            <a class="aa-cartbox-img" href="#"><img src="@item.Produto.ImageURL" alt="#"></a>
            <div class="aa-cartbox-info">
                <h4><a href="#">@item.Produto.Name</a></h4>
                <p>@item.Quantity x @item.TotalAmount</p>
            </div>
            <a class="aa-remove-product" href="@Url.Action("Remove", "MyCart", new { id = item.ProductID})"><span class="fa fa-times"></span></a>
        </li>
    }
}

<li>
    <span class="aa-cartbox-total-title">
        TotalAmount
    </span>
    <span class="aa-cartbox-total-price">
        @ViewBag.TotalAmount
    </span>
</li>

MVC_GerenciadorDeCont/Views/Shared/_Product.cshtml
@model  Business.Produto

<li>
    <figure>
        <a class="aa-product-img" href="@Url.Action("ViewDetails", "Product", new { id = Model.ProductID })"><img src="@Model.ImageURL" alt="#" style="width: 200px; height: 150px;"></a>
        <a class="aa-add-card-btn" href="@Url.Action("AddToCart", "Product", new { id = Model.ProductID })"><span class="fa fa-shopping-cart"></span>Adicione ao Carrinho</a>
        <figcaption>
            <h4 class="aa-product-title"><a href="#">@Model.Name</a></h4>
            <span class="aa-product-price">R$ @Model.UnitPrice,00 </span><span class="aa-product-old-price">               
            </span>
        </figcaption>
    </figure>
    <div class="aa-product-hvr-content">
        <a href="#" data-toggle="tooltip" data-placement="top" title="Add to Wishlist"><span class="fa fa-heart-o"></span></a>
        <a href="@Url.Action("ViewDetails", "Product", new { id = Model.ProductID })" title="View Details" data-toggle="tooltip" data-placement="top"><span class="fa fa-info"></span></a>


    </div>
    @if (Model.AddBadge == true)
        {
            <span class="aa-badge  @Model.OfferBadgeClass" href="#">@Model.OfferTitle</span>
        }
        @{
            TempData["returnURL"] = Request.RawUrl;
        }
</li>

MVC_GerenciadorDeCont/Views/Shared/_Render.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/validacoes.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1 style="color:#fff">Minha Pagina Renderizada </h1>
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding:30px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>