MVC_GerenciadorDeCont/Controllers/CheckOutController.cs
using Business;
using System;
using System.Web.Mvc;

namespace MVC_GerenciadorDeCont.Controllers
{
    public class CheckOutController : Controller
    {

        public ActionResult Index()
        {
            var typePayment = new PaymentType().Lista();
            ViewBag.PayMethod = new SelectList(typePayment, "PayTypeID", "TypeName");
            var data = this.GetDefaultData();
            return View(data);
        }


        public ActionResult PlaceOrder(FormCollection getCheckoutDetails)
        {

            var item = new ShippingDetail();
            int itemCompra = item.Count();

            var item2 = new Payment();
            int itemPagamento = item2.Count();

            var item3 = new Order();
            int itemPedido = item3.Count();


            int shpID = 1;
            if (itemCompra > 0)
            {
                shpID = itemCompra + 1;
            }

            int payID = 1;
            if (itemPagamento > 0)
            {
                payID = itemPagamento + 1;
            }
            int orderID = 1;
            if (itemPedido > 0)
            {
                orderID = itemPedido + 1;
            }

            ShippingDetail shpDetails = new ShippingDetail();
            shpDetails.ShippingID = shpID;
            shpDetails.FirstName = getCheckoutDetails["FirstName"];
            shpDetails.LastName = getCheckoutDetails["LastName"];
            shpDetails.Email = getCheckoutDetails["Email"];
            shpDetails.Mobile = getCheckoutDetails["Mobile"];
            shpDetails.Address = getCheckoutDetails["Address"];
            shpDetails.Province = getCheckoutDetails["Province"];
            shpDetails.City = getCheckoutDetails["City"];
            shpDetails.PostCode = getCheckoutDetails["PostCode"];
            shpDetails.Save();


            Payment pay = new Payment();
            pay.PaymentID = payID;
            pay.Type = Convert.ToInt32(getCheckoutDetails["PayMethod"]);
            pay.Save();

            Order o = new Order();
            o.OrderID = orderID;
            o.CustomerID = TempShpData.UserID;
            o.PaymentID = payID;
            o.ShippingID = shpID;
            o.Discount = Convert.ToInt32(getCheckoutDetails["discount"]);
            o.TotalAmount = Convert.ToInt32(getCheckoutDetails["totalAmount"]);
            o.isCompleted = true;
            o.OrderDate = DateTime.Now;
            o.Save();


            foreach (var OD in TempShpData.items)
            {
                OD.OrderID = orderID;
                OD.Order = Order.BuscaPorId(orderID);
                OD.Produto = Produto.BuscaPorId(OD.ProductID);
                OD.Save();
            }

            return RedirectToAction("Index", "ThankYou");
        }
    }
}

MVC_GerenciadorDeCont/Views/CheckOut/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="~/Content/img/fashion/fashion-header-bg-8.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>Checkout Page</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Checkout</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("PlaceOrder", "CheckOut", FormMethod.Post))
{
    <!-- / catg header banner section -->
    <!-- Cart view section -->
    <section id="checkout">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="checkout-area">
                        <form action="">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="checkout-left">
                                        <div class="panel-group" id="accordion">
                                            <!-- Coupon section -->
                                            <div class="panel panel-default aa-checkout-coupon">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title">
                                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                                            Tem um Cupom?
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="collapseOne" class="panel-collapse collapse in">
                                                    <div class="panel-body">
                                                        <input type="text" placeholder="Codigo do Cupom" class="aa-coupon-code">
                                                        <input type="submit" value="Aplicar Desconto" class="aa-browse-btn">
                                                    </div>
                                                </div>
                                            </div>

                                            <!-- Billing Details -->
                                            <div class="panel panel-default aa-checkout-billaddress">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title">
                                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                                                            Detalhes da Compra / Endreço de Entrega
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="collapseThree" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="FirstName" type="text" required placeholder="Nome*">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="LastName" type="text" required placeholder="Sobrenome*">
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="Email" type="email" required placeholder="E-mail*">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="Mobile" type="tel" required placeholder="Celular*">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <div class="aa-checkout-single-bill">
                                                                    <textarea name="Address" cols="8" required rows="3" placeholder="Endereço*"></textarea>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <div class="aa-checkout-single-bill">
                                                                    <select name="Province">
                                                                        <option value="--">Selecione o Estado</option>
                                                                        <option value="Punjab">Punjab</option>
                                                                        <option value="KPK">KPK</option>
                                                                        <option value="Sindh">Sindh</option>
                                                                        <option value="Balochistan">Balochistan</option>

                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="City" type="text" placeholder="Cidade">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="aa-checkout-single-bill">
                                                                    <input name="PostCode" type="text" placeholder="CEP">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="checkout-right">
                                        <h4>Order Summary</h4>
                                        <div class="aa-order-summary-area">
                                            <table class="table table-responsive">
                                                <thead>
                                                    <tr>
                                                        <th>Produto</th>
                                                        <th>Total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @if (Session["username"] != null)
                                                    {
                                                        foreach (var item in (List<Business.OrderDetail>)@Model)
                                                        {
                                                            
                                                            <tr>
                                                                <td>@item.Produto.Name <strong> x  @item.Quantity</strong></td>
                                                                <td>@item.TotalAmount</td>
                                                            </tr>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <text>Por favor, faça Login</text>
                                                    }
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th>Subtotal</th>
                                                        <td>@ViewBag.SubTotal</td>
                                                    </tr>
                                                    <tr>
                                                        @Html.Hidden("discount", null, new { @value = ViewBag.Discount })
                                                        <th>Desconto</th>
                                                        <td>@ViewBag.Discount</td>
                                                    </tr>
                                                    <tr>
                                                        @Html.Hidden("totalAmount", null, new { @value = ViewBag.TotalAmount })
                                                        <th>Total</th>
                                                        <td>@ViewBag.TotalAmount</td>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                        <h4>Tipo de Pagamento</h4>
                                        <div class="aa-payment-method">

                                            <div class="aa-checkout-single-bill aa-checkout-billaddress">
                                                <div class="form-group">

                                                    <div class="col-md-10">
                                                        @Html.DropDownList("PayMethod", null, htmlAttributes: new { @class = "form-control", @name = "PaymentMethod" })
                                                    </div>
                                                </div>
                                            </div>
                                            <br /><br />
                                            <img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark">
                                            <input type="submit" value="Place Order" class="aa-browse-btn">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- / Cart view section -->
}